---
title: "Background"
editor: visual
link-external-icon: true
link-external-newwindow: true
---

Understanding the importance of estuaries, the federal government established a network of National Estuarine Research Reserves through the Coastal Zone Management Act in 1972. The Guana Tolomato Matanzas National Estuarine Research Reserve (GTMNERR) was designated in 1999 and encompasses more than 30,000 hectares of coastal habitats in Northeast Florida. Currently, GTMNERR is one of 30 reserves established to serve as a living laboratory for staff, students, visiting scientists, and anyone who is interested in learning more about coastal ecosystems. Research conducted throughout the reserve addresses specific coastal management needs that support national, regional, and local interests. To learn more about the GTMNERR, visit <https://floridadep.gov/rcp/nerr-gtm> and <https://coast.noaa.gov/nerrs/reserves/gtm.html>.

In 1995 the National Estuarine Research Reserve System (NERRS) established the System-Wide Monitoring Program (SWMP) to track and understand short-term variability and long-term change within our nation's estuaries. The primary function of SWMP is the standardized collection and analysis of long-term data related to management issues, which helps to better inform decision-makers and improve our understanding of the issues affecting estuaries and coastal watersheds (SWMP Plan, 2011). The longest running components of the SWMP at the GTMNERR are weather and water quality monitoring, which began in December 2000. Newer SWMP protocols for habitat mapping and emergent vegetation were initiated about a decade later.

This report provides a baseline summary of the three longest running components of the SWMP at the GTMNERR: continuous water quality, discrete water quality, and weather. The continuous water quality component is comprised of four fixed monitoring stations, at which automated instruments (data sondes) are deployed to continuously collect information on a suite of water quality parameters. Discrete water samples are collected monthly for nutrients and other parameters at these same four stations, with an additional diel sampler deployed at one station. To complement the water quality data, the GTMNERR also operates and maintains one continuous meteorological station. All SWMP data are publicly available for download through the NERRS Centralized Data Management Office (CDMO). The CDMO supports data management protocols for SWMP and is responsible for ensuring that SWMP data are of high quality and accessible online (<https://www.nerrsdata.org>).

::: callout-important
This report is updated quarterly after the collected data has undergone the secondary quality assurance and quality control (QAQC) process. For more information on the SWMP QAQC process, please visit <http://cdmo.baruch.sc.edu/data/qaqc.cfm>.
:::
