---
title: "Maintenance Notes"
link-external-icon: true
link-external-newwindow: true
execute:
  warning: false
  error: false
filters:
  - lightbox
lightbox: auto
---

## Sonde Failure in Field

One sonde failure ("Irma" SN: 20H100465) and multiple sensor failures (3 Wiped CT, 1 DO, 1 Turbidity, and 1 Central Wiper) occurred during the first quarter. The datasonde will need to be sent in for repair as one of the sensor pins was sheared off in the bulkhead - likely due to excessive power draw from the Central Wiper, coupled with electrolysis. Sensors will all need to be either evaluated (turbidity, central wiper) or replaced (WCT, DO).

SD card failed during deployment of sonde at San Sebastian ("Triton" SN: 13K102679) 11/29/2023 12:00 - 12/12/2023 10:00 which was likely a result of a failing central wiper (SN: 13H102597). Downloaded data file was broken up a bunch of times and wiper kept showing up as 'NaN' in the chunks. Failed in the field after 12/05/2023 15:15. 

## Wiper Brush Fell Off

The wiper brush fell off on the following deployments:

Pine Island:

-   May 23 - June 14, 2023 ("Dorian" SN: 20H100466) central wiper SN: 13D102048
-   November 14 - November 29, 2023 ("Oyster" SN: 17K103253) central wiper SN: 12L101282

San Sebastian:

-   May 2 - May 23, 2023 ("Matthew" SN: 20H100464) central wiper SN: 22A106852
-   August 1 - September 6, 2023 ("Triton" SN: 13K102679) central wiper SN: 13H102597
-   December 12, 2023 - January 10, 2024 ("Megalops" SN: 16J102351) central wiper SN: 22A106852

Pellicer Creek

-   May 16 - June 13, 2023 ("Egret" SN: 15E101700) central wiper SN: 16J100200 *no wiper brush was deployed during this deployment*
-   June 27 - July 19, 2023 ("Egret" SN: 15E101700) central wiper SN: 16J100200

## Weather Station Battery Voltage and Telemetry Troubleshooting

We began having signal issues with the telemetry dropping out at the SWMP weather station in mid-April. After troubleshooting on site on April 24, 2023 with a tech expert from another Reserve, we eliminated the possibility of issues with the data logger and the transmitter. On May 10, 2023, the battery (installed in 2016) was replaced on the station with a 2020 battery and all transmissions and power were successful and consistent.

## Bad Batch

Had a sonde ("Matthew" SN: 20H100464) die two days into it's deployment on July 18, 2023. Investigating the data file revealed a steady and sharp decline in battery voltage with each measurement until insufficient voltage remained to power the sonde through a deployment. At post-calibration it gave “internal battery voltage is below 0.9V per cell” error and after replacing with alternative batteries, passed post-calibration checks. Evaluation revealed no issue with with the sensors or sonde itself. YSI Service Technicians recommended redeploying the sonde in the lab for a couple of days and check the data for rapid battery drain as it could have been faulty batteries. The sonde was deployed for a week in the lab with no data collection or battery power issues. Therefore, it appears it was a bad batch of batteries. In the future, before tossing the batteries into the junk bin, they will be evaluated with a volt meter. Unfortunately, they were tossed into the bin first this time and they could not be evaluated.

## Depth dropout 

The depth dropped out early in deployment of sonde ("Dorian" SN: 20H100466) from October 16 - November 14, 2023 at Pine Island and the depth sensor disconnected from the data sonde. No depth data was collected during deployment, nor was the depth sensor connected and readable during post-calibrations. After contacting YSI for tips on how to reconnect to the sensor (they are internal to the instruments), performed the suggested hard reset by removing the batteries from the compartment and reconnected to EXO Handheld - the depth sensor came back. When attempted to calibrate the sonde for redeployment on November 27, the depth sensor failed to stabilize. The sonde was not used and was packed up for evaluation and repair.

The depth sensor dropped from deployment of sonde ("Egret" SN: 15E101700) from December 12, 2023 - January 10, 2024 at Pellicer Creek. This resulted in a broken deployment file at 12/17/23 04:30 in which the depth sensor was completely missing from the second half of this split file. During post-calibrations, the battery compartment was reset (removed battery cap and replaced it) and the depth sensor was reconnected to the datasonde. Post-calibration values were able to be collected and a calibration test of the sensor showed that it was able to be stabilized. Therefore, this sensor and sonde will be redeployed.

## Sticky wiper

During the November 29 - December 12 deployment at Pine Island, the central wiper (SN: 13D102048) brush locked over Port 5 sensor position and the central wiper sensor lost connection to the data sonde. The sensor seemed to begin having issues 12/2/2023 21:30:47 and dropped entirely from the deployment/sonde 12/12/2023 11:45:47 upon retrieval.

## Data file broken up

The data file downloaded from the November 29 - December 12 deployment at Fort Matanzas was broken into two sections split at 12/09/23 00:15 - 12/09/23 00:30. It is unclear as to the cause of this split.