---
title: "Quality Assurance/Quality Control (QA/QC)"
link-external-icon: true
link-external-newwindow: true
---

From 2003--2006, SWMP data underwent a two-step QA/QC process (secondary and tertiary) using protocols outlined in the CDMO's Data Management Manual (NERRS, 2006). The secondary QA/QC process was performed by GTMNERR staff and involved performing basic statistical analysis, processing the data using macros distributed by the CDMO, and plotting data to look for suspect or anomalous data. Anomalous data were evaluated to determine whether values were: 1) outside the expected range for the site, or 2) outside the range of measurements established by YSI for the sensors. Data were investigated for validity based on weather and field observations, quality control checks, graphs, and instrument diagnostics. Yearly data files were compiled, and data were deleted if anomalies were attributed to sensor malfunctions. Other anomalous data were marked as suspect in the accompanying yearly metadata document. Both the annual data file and metadata were submitted to the CDMO for archiving and review. The CDMO evaluated the reserve's findings by performing a tertiary review process. The tertiary process included evaluating the files for completeness, ensuring that supporting documentation was submitted, and offering suggestions for improvements to the data. All data files collected prior to 2007 are referred to as "historic" data files by the CDMO. Beginning in January 2007 and continuing to present, all SWMP data files undergo a three-step QA/QC protocol outlined in the CDMO Data Management Manual (NERRS, 2015). In addition to the secondary and tertiary processes listed above, data files undergo a primary QA/QC process, in which an automated QA/QC is performed by the CDMO upon the upload of the raw data file using the CDMO's Data Upload Service.

Once tertiary review is completed for data files, they are referred to as "authenticated" data. All data files used in this report have been authenticated with the exception of nutrient data collected in 2013 and 2015-present, which have not undergone tertiary review. Historic data files (2003--2006) were edited to include the updated QA/QC protocols that were implemented by the CDMO in 2007. Standardized QA/QC flags and codes were applied to the historic data files using finalized metadata reports. These files were updated to include suspect data flags and codes to keep consistency among all data files. Rejected and suspect data were removed from the data files prior to analyses.

::: callout-important
All water quality and weather data used in this report are downloadable through the NERRS Centralized Data Management Office using their [data portals](http://cdmo.baruch.sc.edu/get/landing.cfm). However, much of the nutrient data presented in this report is not fully available through the CDMO. For those wishing to access this data, please contact the GTM Research Reserve SWMP Manager Shannon Dunnigan at Shannon.Dunnigan\@FloridaDEP.gov for the data.
:::
